### 사원 전체 조회
GET http://localhost:8001/payroll/all-emplpayroll

### 지급 항목 조회
GET http://localhost:8001/payroll/earning-category

### 공제 항목 조회
GET http://localhost:8001/payroll/deduction-category

### 사원 개별 조회
GET http://localhost:8001/payroll/mypay/201211001

### 사원 급여 자료 입력
POST http://localhost:8001/payroll/save-emplpay
Content-Type: application/json

{
  "employeeId": 202311018,
  "payrollDate": "2024-07-25",
  "payStubPath": "",
  "earningRecordList": [
    {
      "earningCategoryId": 101,
      "amount": 2500000
    }
  ],
  "deductionRecordList": [
    {
      "deductionCategoryId": 501,
      "amount": 112500
    }
  ]
}