spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/officeerp
    username : panda
    password : panda
  mail:
    username: mydogduri@naver.com
    password: "!k04030228"
    host: smtp.naver.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8001

#image:
#  image-url: http://localhost:8001/productimgs/
#  image-dir: src/main/resources/static/productimgs
approvalDocumentAttachedFile:
  file-url: http://localhost:8001/productimgs/
  file-dir: src/main/resources/static/approvalDocument
image:
  image-url: http://localhost:8001/image/
  image-dir: src/main/resources/static/uploadFiles

jwt:
  secret: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923
  access:
    expiration: 360000000000000000
  refresh:
    expiration: 604800000